[package]
name = "rust-engine"
version = "0.1.0"
authors = ["Tad Scritchfield <tscritchfield@digitalairstrike.com>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }

[dependencies.sdl2]
version = "0.32.2"
#features = ["bundled", "static-link"]

[features]
gl_debug = ["gl/debug"]